services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Newageerp\SfControlpanel\Controller\ConfigBuilderController:
    arguments: [ ]
  Newageerp\SfControlpanel\Controller\ConfigCacheController:
    arguments: [ ]
  Newageerp\SfControlpanel\Controller\ConfigDbController:
    arguments: [ ]
  Newageerp\SfControlpanel\Controller\ConfigDefaultsController:
    arguments: [ ]
  Newageerp\SfControlpanel\Controller\ConfigEditController:
    arguments: [ ]
  Newageerp\SfControlpanel\Controller\ConfigTabsController:
    arguments: [ ]
  Newageerp\SfControlpanel\Controller\ConfigViewController:
    arguments: [ ]
  Newageerp\SfControlpanel\Controller\ConfigWidgetsController:
    arguments: [ ]
  Newageerp\SfControlpanel\Controller\ConfigMenuController:
    arguments: [ ]
  Newageerp\SfControlpanel\Controller\ConfigMenuFolderController:
    arguments: [ ]
  Newageerp\SfControlpanel\Controller\ConfigMenuTitleController:
    arguments: [ ]
  Newageerp\SfControlpanel\Controller\ConfigBadgeController:
    arguments: [ ]
  Newageerp\SfControlpanel\Service\MenuService:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\PropertiesUtils:
    arguments: [ ]

  Newageerp\SfControlpanel\Console\In\InLocalConfigSyncEntitiesConsole:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InLocalConfigSyncFieldsConsole:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InLocalConfigSyncPdfsConsole:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InLocalConfigSyncStatusesConsole:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InLocalConfigSyncUsersPermissionsConsole:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InLocalConfigSyncVariablesConsole:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InPathMapConsole:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InGeneratorMenu:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InGeneratorTabs:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InGeneratorStatuses:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InGeneratorEnums:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InGeneratorBadges:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\In\InRunAll:
    tags:
      - { name: 'console.command' }

  Newageerp\SfControlpanel\Console\Out\OutCacheDocJsonConsole:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\Out\OutLocalConfigBuildMockConsole:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\Out\OutLocalConfigSyncPropertiesConsole:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\Out\OutLocalConfigSyncSchemasConsole:
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\Out\OutRunAll:
    tags:
      - { name: 'console.command' }