services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Newageerp\SfControlpanel\Controller\*:
    arguments: [ ]
  Newageerp\SfControlpanel\Service\*:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\PropertiesUtils:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\EntitiesUtils:
    arguments: [ ]

  Newageerp\SfControlpanel\Console\Maker\MakePluginWithServiceAndMessageHandler:
    tags:
      - { name: 'console.command' }

  Newageerp\SfControlpanel\Console\In\*:
    tags:
      - { name: 'console.command' }

  Newageerp\SfControlpanel\Console\Out\*:
    tags:
      - { name: 'console.command' }
