services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Newageerp\SfControlpanel\Controller\:
    resource: '../Controller/*'
    arguments: [ ]
  Newageerp\SfControlpanel\Service\:
    resource: '../Service/*'
    arguments: [ ]
  Newageerp\SfControlpanel\Console\PropertiesUtils:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\EntitiesUtils:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\PropertiesUtilsV3:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\EntitiesUtilsV3:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\TabsUtilsV3:
    arguments: [ ]

  Newageerp\SfControlpanel\Console\Maker\MakePluginWithServiceAndMessageHandler:
    tags:
      - { name: 'console.command' }

  Newageerp\SfControlpanel\Console\In\:
    resource: '../Console/In/*'
    tags:
      - { name: 'console.command' }
  Newageerp\SfControlpanel\Console\V3\:
    resource: '../Console/V3/*'
    tags:
      - { name: 'console.command' }

  Newageerp\SfControlpanel\Console\Out\:
    resource: '../Console/Out/*'
    tags:
      - { name: 'console.command' }
